export {default as Feed} from './News/Feed'
export {default as Navbar} from './Navbar'
export {default as SingleArticle} from './News/SingleArticle'
export {default as Interests} from './Onboarding/interests'
export {default as Resources} from './Resources/resources'
export {default as Splash} from './SplashScreen/splash'